apiVersion: v1
kind: ConfigMap
metadata:
  name: arteci-api-config
  namespace: arteci
data:
  PORT: "${API_PORT}"
  UI_DIR: /ui
  MINIO_ENDPOINT: minio-service
  MINIO_PORT: "${MINIO_PORT}"
  MINIO_USE_SSL: "${MINIO_USE_SSL}"
  MINIO_BUCKET: "${MINIO_BUCKET}"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-otel-collector.monitoring.svc.cluster.local:4317
  OTEL_SERVICE_NAME: "${OTEL_SERVICE_NAME}"
