apiVersion: v1
kind: Service
metadata:
  name: arteci-api-service
  namespace: arteci
spec:
  selector:
    app: arteci-api
  ports:
    - port: ${API_PORT}
      targetPort: ${API_PORT}
      protocol: TCP
  type: LoadBalancer
