apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: arteci
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: ${MINIO_PORT}
      targetPort: ${MINIO_PORT}
    - name: console
      port: ${MINIO_CONSOLE_PORT}
      targetPort: ${MINIO_CONSOLE_PORT}
  type: LoadBalancer
