apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: arteci
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args: ["server", "/data", "--address", ":${MINIO_PORT}", "--console-address", ":${MINIO_CONSOLE_PORT}"]
          ports:
            - containerPort: ${MINIO_PORT}
            - containerPort: ${MINIO_CONSOLE_PORT}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: arteci-api-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arteci-api-secret
                  key: MINIO_SECRET_KEY
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: ${MINIO_PORT}
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: arteci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
