# Repo:  helm repo add signoz https://charts.signoz.io

global:
  storageClass: ""

postgresql:
  enabled: true
  auth:
    database: signoz
    username: signoz
    password: signoz
  primary:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

clickhouseKeeper:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

clickhouse:
  replicaCount: 1
  persistence:
    enabled: true
    size: 50Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi


signoz:
  replicaCount: 1
  env:
    TELEMETRY_ENABLED: "false"
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

ingester:
  replicaCount: 1
  service:
    type: ClusterIP
    ports:
      grpc: 4317
      http: 4318
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
